### PR TITLE
add build flag to allow disable deepin ocr

### PR DESCRIPTION
**Pull request by wineee**
1. 处理新版 libraw 编译失败
2. 添加编译参数使 ocr 可选

### CODE REVIEW

**Review by Decodetalkers — COMMENTED** [review]
+1

**Comment by Decodetalkers** [comment]
libraw他们好像没有pkgcheck

**Comment by wineee** [comment]
> pkgcheck



> libraw他们好像没有pkgcheck

https://github.com/linuxdeepin/deepin-image-viewer/blob/1511990072246b553074791705119a388425f3a2/qimage-plugins/libraw/CMakeLists.txt#L17

**Comment by wineee** [comment]
outdated

**Pull request closed without merging**
